# **Introduction to Numpy Python Library**

Install Numpy Library using pip:

In [ ]:
# !pip install numpy

Import numpy:

In [8]:
import numpy as np

## What is an Array?

In computer programming, an array is a structure for storing and retrieving data. It allows you to store multiple values of the same data type under a single variable name and access them using an index.

In NumPy, an array refers to the `ndarray` object, which is the fundamental data structure provided by the library. It is a homogeneous, multidimensional array of fixed-size items, meaning all elements within the array must be of the same data type.

### 1D array

- A one-dimensional (1D) array is a linear data structure that stores a sequence of elements, all of the same data type, in a contiguous block of memory. 
- Think of it like a single row of boxes, where each box holds a value, and all boxes are placed next to each other. 

Creating 1D array:

In [18]:
# create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array_1d)
print("Shape:", array_1d.shape)

[1 2 3 4 5 6 7 8]
Shape: (8,)


### 2D array

- A two-dimensional (2D) array is a data structure that organizes elements in a grid-like format, consisting of rows and columns. 
- You can think of it as a table or a matrix, where each cell can hold a value, and the position of the cell is defined by its row and column indices.

Creating a 2D array:

In [17]:
# create 2D array
array_2d = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15]])

print(array_2d)
print("Shape:", array_2d.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Shape: (3, 5)


### 3D array

- A three-dimensional (3D) array is a data structure that organizes elements in a cube-like format, consisting of depth, rows, and columns.
- You can think of it as a stack of tables or a collection of matrices, where each cell can hold a value, and the position of the cell is defined by its depth, row, and column indices.

Creating 3D array:

In [21]:
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],      # First matrix (2x3)
    [[7, 8, 9], [10, 11, 12]]    # Second matrix (2x3)
])

print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


> - 1D array → a list of numbers (a line)
> - 2D array → a list of lists (a table / matrix)
> - 3D array → a list of 2D arrays (a "stack" of tables)

---

## Arrays Filled with Specific Values

In [43]:
# Array of zeros
arr_zeros = np.zeros((2, 3))   # 2 rows and 3 columns
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# Array of ones
arr_ones = np.ones((2, 2))   # 2 rows and 2 columns
arr_ones

array([[1., 1.],
       [1., 1.]])

In [41]:
# Array filled with a specific value
arr_tens = np.full((3, 4), 10)  # 3 x 4 array filled with 10
arr_tens

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

## Arrays with a Range of Values

In [40]:
# Array with evenly spaced values within a range
arr_arange = np.arange(0, 8, 2) # start 0, stop 7, step 2
arr_arange

array([0, 2, 4, 6])

In [44]:
# Array with a specified number of evenly spaced values over an interval
arr_linspace = np.linspace(0, 1, 5)  # 5 values between 0 and 1 (inclusive)
arr_linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Empty or Identity Arrays

In [50]:
# Empty array (uninitialized values)
arr_empty = np.empty((3, 3))
arr_empty

array([[15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.]])

In [53]:
# Identity matrix (for square 2D arrays)
arr_identity = np.eye(3)  # 3x3 identity matrix
arr_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Arrays with Random Values

In [ ]:
# Create a 1-D array of 5 random floats
arr_1d_float = np.random.rand(5)
arr_1d_float

array([0.44106964, 0.24118644, 0.6195356 , 0.24094638, 0.59428448])

In [75]:
# Create a 1-D random array of shape 2 x 3
arr_2d_float = np.random.rand(2, 3)
arr_2d_float

array([[0.10123911, 0.8246729 , 0.41038805],
       [0.44597513, 0.74187469, 0.72374493]])

In [80]:
# Create a 1d array of 8 random integers between 0 (inclusive) and 10 (exclusive)
arr_1d_int = np.random.randint(0, 10, size=8)
arr_1d_int

array([7, 5, 5, 0, 4, 4, 3, 7], dtype=int32)

---

Check data type of an array:

In [ ]:
arr_a = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

arr_a.dtype

dtype('int64')

In [86]:
arr_b = np.array([[1.5, 2.1, 3, 4],
                [5, 6, 7.9, 8]])

arr_b.dtype

dtype('float64')

In [92]:
arr_c = np.array([['a', 'b', 'c'],
                ['d', 'e', 'f']])

arr_c.dtype

dtype('<U1')

Dimension, length shape and size of an array:

In [93]:
# initializing 1D, 2D and 3D arrays

# 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# 2D array
array_2d = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15]])
# 3D array
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],    
    [[7, 8, 9], [10, 11, 12]]    
])

In [95]:
# check for array dimension
print(array_1d.ndim)
print(array_2d.ndim)
print(array_3d.ndim)

1
2
3


In [97]:
# length of arr
print(len(array_1d))
print(len(array_2d))
print(len(array_3d))

8
3
2


In [98]:
# shape of arr
print(array_1d.shape)
print(array_2d.shape)
print(array_3d.shape)

(8,)
(3, 5)
(2, 2, 3)


In [101]:
# array size (total number of elements)
array_2d.size

15

## Some Basic Operations

In [111]:
# initializing arrays

a = np.array([12, 14, 16, 18])
b = np.array([[1, 3, 5, 7], [9, 11, 13, 14]])

In [112]:
a

array([12, 14, 16, 18])

In [113]:
b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 14]])

Array subtraction:

In [114]:
# subtraction
arr_subtraction = a - b
arr_subtraction

array([[11, 11, 11, 11],
       [ 3,  3,  3,  4]])

Array addition:

In [115]:
# addition
arr_add = a + b
arr_add

array([[13, 17, 21, 25],
       [21, 25, 29, 32]])

In [116]:
# array ddition using 'np.add()'
np.add(a, b)

array([[13, 17, 21, 25],
       [21, 25, 29, 32]])

Array multiplication:

In [117]:
# multiplication
array_multiplication = a * b
array_multiplication

array([[ 12,  42,  80, 126],
       [108, 154, 208, 252]])

Array division:

In [118]:
# division
array_division = a / b
array_division

array([[12.        ,  4.66666667,  3.2       ,  2.57142857],
       [ 1.33333333,  1.27272727,  1.23076923,  1.28571429]])

Taking square of array elements:

In [119]:
a

array([12, 14, 16, 18])

In [123]:
# square of each element
arr_square = a ** 2
arr_square

array([144, 196, 256, 324])

In [124]:
# cube
arr_cube = a ** 3
arr_cube

array([1728, 2744, 4096, 5832])

---