# **Matrices in NumPy**

In [1]:
# importing numpy
import numpy as np

## What are Matrices?

Matrices are basically 2-D arrays with rows and columns.

## Creating a Matrix

- We can pass list of lists to create a Matrix (2D array) in numpy:

In [2]:
# creating a 2 x 3 matrix
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

- Creating matrix of bigger size:

In [3]:
b = np.arange(5, 501, 5).reshape(10, 10)
b

array([[  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75,  80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125, 130, 135, 140, 145, 150],
       [155, 160, 165, 170, 175, 180, 185, 190, 195, 200],
       [205, 210, 215, 220, 225, 230, 235, 240, 245, 250],
       [255, 260, 265, 270, 275, 280, 285, 290, 295, 300],
       [305, 310, 315, 320, 325, 330, 335, 340, 345, 350],
       [355, 360, 365, 370, 375, 380, 385, 390, 395, 400],
       [405, 410, 415, 420, 425, 430, 435, 440, 445, 450],
       [455, 460, 465, 470, 475, 480, 485, 490, 495, 500]])

## Indexing and Slicing a matrix

We can index and slice a matrix using row and column indices.

In [4]:
b

array([[  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75,  80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125, 130, 135, 140, 145, 150],
       [155, 160, 165, 170, 175, 180, 185, 190, 195, 200],
       [205, 210, 215, 220, 225, 230, 235, 240, 245, 250],
       [255, 260, 265, 270, 275, 280, 285, 290, 295, 300],
       [305, 310, 315, 320, 325, 330, 335, 340, 345, 350],
       [355, 360, 365, 370, 375, 380, 385, 390, 395, 400],
       [405, 410, 415, 420, 425, 430, 435, 440, 445, 450],
       [455, 460, 465, 470, 475, 480, 485, 490, 495, 500]])

- Accessing a Single Element:

In [5]:
# accessing element by row, col index
print(b[3,3])  # 170
print(b[2,4])  # 125
print(b[9,4])  # 475

170
125
475


- Accessing Rows

In [6]:
print(b[0])      # First row -> [5 10 15 ... 50]
print(b[4])      # Fifth row -> [205 210 ... 250]
print(b[-1])     # Last row -> [455 460 ... 500]

[ 5 10 15 20 25 30 35 40 45 50]
[205 210 215 220 225 230 235 240 245 250]
[455 460 465 470 475 480 485 490 495 500]


- Accessing Columns

In [7]:
print(b[:, 0])   # First column -> [5 55 105 ... 455]
print(b[:, 4])   # Fifth column -> [25 75 125 ... 475]
print(b[:, -1])  # Last column -> [50 100 150 ... 500]

[  5  55 105 155 205 255 305 355 405 455]
[ 25  75 125 175 225 275 325 375 425 475]
[ 50 100 150 200 250 300 350 400 450 500]


- Slicing Submatrices

**Syntax:** `[row_start:row_end, col_start:col_end]`

In [8]:
print(b[0:3, 0:3])

[[  5  10  15]
 [ 55  60  65]
 [105 110 115]]


In [9]:
b

array([[  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75,  80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125, 130, 135, 140, 145, 150],
       [155, 160, 165, 170, 175, 180, 185, 190, 195, 200],
       [205, 210, 215, 220, 225, 230, 235, 240, 245, 250],
       [255, 260, 265, 270, 275, 280, 285, 290, 295, 300],
       [305, 310, 315, 320, 325, 330, 335, 340, 345, 350],
       [355, 360, 365, 370, 375, 380, 385, 390, 395, 400],
       [405, 410, 415, 420, 425, 430, 435, 440, 445, 450],
       [455, 460, 465, 470, 475, 480, 485, 490, 495, 500]])

In [10]:
print(b[3:8, 1:4])

[[160 165 170]
 [210 215 220]
 [260 265 270]
 [310 315 320]
 [360 365 370]]


In [11]:
# slicing the matrix
b[1:2, 4:5]

array([[75]])

- Step Slicing

We can also use steps: `[start:end:step]`.

In [12]:
# Slicing every 2nd row and column
c = b[::2, ::2]
c

array([[  5,  15,  25,  35,  45],
       [105, 115, 125, 135, 145],
       [205, 215, 225, 235, 245],
       [305, 315, 325, 335, 345],
       [405, 415, 425, 435, 445]])

---

## max(), min(), sum()

We can use the `max()`, `min()`, and `sum()` functions to find the maximum, minimum, and sum of all elements in a NumPy array.



In [13]:
b

array([[  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75,  80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125, 130, 135, 140, 145, 150],
       [155, 160, 165, 170, 175, 180, 185, 190, 195, 200],
       [205, 210, 215, 220, 225, 230, 235, 240, 245, 250],
       [255, 260, 265, 270, 275, 280, 285, 290, 295, 300],
       [305, 310, 315, 320, 325, 330, 335, 340, 345, 350],
       [355, 360, 365, 370, 375, 380, 385, 390, 395, 400],
       [405, 410, 415, 420, 425, 430, 435, 440, 445, 450],
       [455, 460, 465, 470, 475, 480, 485, 490, 495, 500]])

### Using `min()`

In [14]:
# minimum value in 'b' array
b.min()

np.int64(5)

In [ ]:
# minimum value in each row column
b.min(axis=1)

array([  5,  55, 105, 155, 205, 255, 305, 355, 405, 455])

In [21]:
# minimum value in each column
b.min(axis=0)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

### Using `max()`

In [ ]:
# maximum value in 'b' array
b.max()

np.int64(500)

In [24]:
# maximum value in each row
b.max(axis=1)

array([ 50, 100, 150, 200, 250, 300, 350, 400, 450, 500])

In [44]:
# maximum value in each column
b.max(axis=0)

array([455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

### Using `sum()`

In [16]:
# total sum of values in 'b' array
b.sum()

np.int64(25250)

In [ ]:
# sum of all values by row
b.sum(axis=1)

array([ 275,  775, 1275, 1775, 2275, 2775, 3275, 3775, 4275, 4775])

In [ ]:
# sum of all values by column
b.sum(axis=0)

array([2300, 2350, 2400, 2450, 2500, 2550, 2600, 2650, 2700, 2750])

---

## Important Operations on Matrices

In [68]:
# creating matrices
A = np.arange(2, 21, 2).reshape(5,2)
B = np.arange(1, 21, 2).reshape(5,2)

In [69]:
A

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [70]:
B

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

- Matrix Addition

Add corresponding elements:

In [72]:
C = A + B
C

array([[ 3,  7],
       [11, 15],
       [19, 23],
       [27, 31],
       [35, 39]])

- Matrix Subtraction

Subtract corresponding elements:

In [73]:
C = A - B
C

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

- Element-wise Multiplication

Multiply corresponding elements:

In [75]:
C = A * B
C

array([[  2,  12],
       [ 30,  56],
       [ 90, 132],
       [182, 240],
       [306, 380]])

- Scalar Multiplication / Division

Multiply or divide the whole matrix by a number:

In [79]:
# multiplication
C = 3 * A
print(C)
 
# Division
D = 3 / A
print(D)

[[ 6 12]
 [18 24]
 [30 36]
 [42 48]
 [54 60]]
[[1.5        0.75      ]
 [0.5        0.375     ]
 [0.3        0.25      ]
 [0.21428571 0.1875    ]
 [0.16666667 0.15      ]]


- Element-wise Division

Divide elements one by one:

In [82]:
C = A / B
C

array([[2.        , 1.33333333],
       [1.2       , 1.14285714],
       [1.11111111, 1.09090909],
       [1.07692308, 1.06666667],
       [1.05882353, 1.05263158]])

- Stack arrays vertically or horizontally:

In [85]:
arr = np.arange(0, 46, 5).reshape(2, 5) # create 2 x 5 matrix

arr

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [ ]:
# stack array vertically 
np.vstack((arr, np.array([50, 55, 60, 65, 70])))

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70]])

In [100]:
# stack array horizontally

arr2 = np.array([[50], [55]])

np.hstack((arr, arr2))

array([[ 0,  5, 10, 15, 20, 50],
       [25, 30, 35, 40, 45, 55]])

- Reverse an array

In [101]:
arr

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [105]:
# revering an array
reversed_arr = np.flip(arr)
reversed_arr

array([[45, 40, 35, 30, 25],
       [20, 15, 10,  5,  0]])

- Transposing a matrix

It’s common to need to transpose your matrices. NumPy arrays have the property `T` that allows you to transpose a matrix.

In [113]:
arr = np.arange(10, 101, 10).reshape(5, 2)
arr

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [114]:
# taking transpose 
arr_T = arr.T
arr_T

array([[ 10,  30,  50,  70,  90],
       [ 20,  40,  60,  80, 100]])

---

Let's connect on Linkedin:- [linkedin.com/in/iamahsanalirajpoot](https://www.linkedin.com/in/iamahsanalirajpoot)
